# Generated by Django 5.1.5 on 2025-03-30 14:45

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='نام دسته بندی')),
                ('url_name', models.CharField(max_length=25, verbose_name='نام در آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='نام تگ')),
                ('url_name', models.CharField(max_length=100, verbose_name='نام تگ در آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='Images/', verbose_name='عکس اصلی')),
                ('short_info', models.CharField(max_length=255, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن خبر')),
                ('data', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسندخ مقاله')),
                ('categories', models.ManyToManyField(to='news_module.articlecategories', verbose_name='دسته بندی ها')),
                ('tags', models.ManyToManyField(to='news_module.articletag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
