# Generated by Django 6.0.8 on 2026-09-06 04:55

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='نام تگ')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تگ مقاله',
                'verbose_name_plural': 'تگ های مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=25, null=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_child', to='news_module.articlecategories', verbose_name='دسته بندی والد(اختیاری)')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='Images/BLog', verbose_name='عکس اصلی')),
                ('short_info', models.CharField(max_length=255, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن خبر')),
                ('data', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسندخ مقاله')),
                ('categories', models.ManyToManyField(to='news_module.articlecategories', verbose_name='دسته بندی ها')),
                ('tags', models.ManyToManyField(related_name='article_list_by_tag', to='news_module.articletag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', 'تایید شده'), ('rejected', 'رد شده'), ('pending', 'در انتظار بررسی')], default='pending', max_length=100, verbose_name='وضعیت نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن نظر')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_module.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_module.articlecomment', verbose_name='نظر والد (اختیاری)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر برای مقاله',
                'verbose_name_plural': 'نظرات برای مقاله ها',
            },
        ),
    ]
