# Generated by Django 6.0.8 on 2026-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن نظر'),
        ),
    ]
