# Generated by Django 5.1.5 on 2025-03-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'تگ مقاله', 'verbose_name_plural': 'تگ های مقالات'},
        ),
        migrations.RemoveField(
            model_name='articlecategories',
            name='url_name',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='url_name',
        ),
        migrations.AddField(
            model_name='articlecategories',
            name='slug',
            field=models.SlugField(max_length=25, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Images/BLog', verbose_name='عکس اصلی'),
        ),
    ]
