# Generated by Django 5.1.5 on 2025-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0002_alter_article_options_alter_articletag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=25, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, verbose_name='اسلاگ'),
        ),
    ]
