# Generated by Django 5.1.5 on 2025-03-31 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0003_alter_articlecategories_slug_alter_articletag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_module.articlecategories', verbose_name='دسته بندی والد(اختیاری)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article_list_by_tag', to='news_module.articletag', verbose_name='تگ ها'),
        ),
    ]
