# Generated by Django 5.1.5 on 2025-03-31 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0004_articlecategories_parent_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_child', to='news_module.articlecategories', verbose_name='دسته بندی والد(اختیاری)'),
        ),
    ]
