# Generated by Django 5.1.5 on 2025-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0005_alter_articlecategories_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategories',
            name='slug',
            field=models.SlugField(max_length=25, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='اسلاگ'),
        ),
    ]
