# Generated by Django 5.1.4 on 2025-03-29 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی های محصول'},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'حداقل موجودی کالا ۰ میباشد!')], verbose_name='تعداد موجودی'),
        ),
    ]
