# Generated by Django 5.1.4 on 2025-03-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_brand_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='کالا جدید است'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(upload_to='Images/product', verbose_name='تصویر محصول'),
        ),
    ]
