# Generated by Django 5.1.4 on 2025-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0007_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصولات",
            },
        ),
        migrations.AddField(
            model_name="productgallery",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
        ),
    ]
