# Generated by Django 5.1.4 on 2025-04-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0008_alter_productgallery_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "گالری محصول",
                "verbose_name_plural": "گالری محصولات",
            },
        ),
        migrations.RenameField(
            model_name="productgallery",
            old_name="image",
            new_name="banner",
        ),
    ]
