# Generated by Django 5.1.4 on 2025-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0010_productcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="info",
            field=models.TextField(null=True, verbose_name="توضیحات"),
        ),
    ]
