# Generated by Django 5.1.4 on 2025-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0011_product_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, verbose_name="نام تگ")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, null=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "تگ محصول",
                "verbose_name_plural": "تگ های محصولات",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="product_tags",
                to="product_module.productcategory",
                verbose_name="دسته بندی ها",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                to="product_module.producttag", verbose_name="تگ های محصول"
            ),
        ),
    ]
