# Generated by Django 5.1.4 on 2025-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0012_producttag_alter_product_categories_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                to="product_module.productcategory", verbose_name="دسته بندی ها"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="product_tags",
                to="product_module.producttag",
                verbose_name="تگ های محصول",
            ),
        ),
    ]
