# Generated by Django 5.1.4 on 2025-04-10 15:57

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0013_alter_product_categories_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomment",
            name="data",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ",
            ),
            preserve_default=False,
        ),
    ]
