# Generated by Django 5.1.4 on 2025-04-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0014_productcomment_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcomment",
            old_name="data",
            new_name="date",
        ),
    ]
