# Generated by Django 5.1.4 on 2025-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0016_productcomment_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomment",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="تایید شده / نشده "),
        ),
    ]
