# Generated by Django 5.1.4 on 2025-04-10 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0017_alter_productcomment_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomment",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(
                        5, "امتیاز نمیتواند بیشتر از ۵ باشد"
                    ),
                    django.core.validators.MinValueValidator(
                        0, "امتیاز نمیتواند کمتر از ۰ باشد"
                    ),
                ],
                verbose_name="امتیاز کاربر",
            ),
            preserve_default=False,
        ),
    ]
