# Generated by Django 5.1.4 on 2025-07-04 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0018_productcomment_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomment",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "تایید شده"),
                    ("pending", "در انتظار تایید"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=255,
                verbose_name="وضعیت کامنت",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.BigIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "حداقل مبلغ محصول ۰ میباشد!"
                    )
                ],
                verbose_name="مبلغ",
            ),
        ),
    ]
