# Generated by Django 5.1.4 on 2025-07-05 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0019_productcomment_status_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomment",
            name="score",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        5, "امتیاز نمیتواند بیشتر از ۵ باشد"
                    ),
                    django.core.validators.MinValueValidator(
                        0, "امتیاز نمیتواند کمتر از ۰ باشد"
                    ),
                ],
                verbose_name="امتیاز کاربر",
            ),
        ),
    ]
