# Generated by Django 5.1.4 on 2025-07-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0020_alter_productcomment_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomment",
            name="has_unread_reply",
            field=models.BooleanField(
                default=False, verbose_name="داشتن پاسخ خوانده نشده"
            ),
        ),
        migrations.AlterField(
            model_name="productcomment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال بودن / نبودن"),
        ),
    ]
