# Generated by Django 6.0.8 on 2026-09-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_productcomment_has_unread_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='product_module.brand', verbose_name='برند'),
        ),
    ]
