# Generated by Django 6.0.8 on 2026-09-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد سفارش از این محصول'),
        ),
    ]
