# Generated by Django 5.1.4 on 2025-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=150, verbose_name='رمز عبور')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('random_string', models.CharField(max_length=72, verbose_name='عبارت فعال سازی')),
            ],
            options={
                'verbose_name': 'کاربر موقت',
                'verbose_name_plural': 'کاربران موقت',
            },
        ),
    ]
