# Generated by Django 6.0.8 on 2026-09-12 06:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_activation_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان فعال سازی حساب'),
        ),
    ]
