# Generated by Django 5.1.4 on 2025-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
