# Generated by Django 6.0.8 on 2026-09-09 06:39

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
        migrations.AddField(
            model_name='user',
            name='account_activated',
            field=models.BooleanField(default=False, verbose_name='حساب فعال شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_code',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='عبارت فعال سازی'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_code_sent_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ارسال کد فعال سازی ایمیل'),
        ),
    ]
