# Generated by Django 5.1.4 on 2025-04-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_tempuser_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempuser',
            old_name='data',
            new_name='date',
        ),
    ]
