# Generated by Django 6.0.8 on 2026-09-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_user_account_activation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_code_sent_date',
        ),
    ]
