# Generated by Django 6.0.8 on 2026-09-12 06:53

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_remove_user_active_code_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_code_sent_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ارسال کد فعال سازی'),
        ),
    ]
