# Generated by Django 5.1.4 on 2025-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_rename_data_tempuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
