# Generated by Django 5.1.4 on 2025-04-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_alter_tempuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
