# Generated by Django 5.1.4 on 2025-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0007_user_address_user_phone_number'),
        ('product_module', '0005_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.product', verbose_name='کالاهای مورد علاقه'),
        ),
    ]
