# Generated by Django 5.1.4 on 2025-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0008_user_favorite_products'),
        ('product_module', '0005_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='product_module.product', verbose_name='کالاهای مورد علاقه'),
        ),
    ]
