# Generated by Django 6.0.8 on 2026-09-06 04:55

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', django_jalali.db.models.jDateTimeField(null=True, verbose_name='تاریخ پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('pending_review', 'در انتظار بررسی'), ('preparing', 'در حال آماده سازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('returned', 'مرجوعی')], default='pending_payment', max_length=255, verbose_name='وضعیت سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش / سبد خرید',
                'verbose_name_plural': 'سفارش ها / سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='orderProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('finally_price', models.BigIntegerField(null=True, verbose_name='قیمت نهایی محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.ordermodel', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'کالای سبد خرید',
                'verbose_name_plural': 'کالاهای سبد خرید',
            },
        ),
    ]
