# Generated by Django 5.1.4 on 2025-04-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_module", "0001_initial"),
        ("product_module", "0018_productcomment_score"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="orderProduct",
            new_name="orderProductModel",
        ),
    ]
