# Generated by Django 6.0.8 on 2026-09-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه پرداخت'),
        ),
    ]
