# Generated by Django 5.1.4 on 2025-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_module", "0002_rename_orderproduct_orderproductmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="paid_data",
            new_name="paid_date",
        ),
    ]
