# Generated by Django 6.0.8 on 2026-09-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_ordermodel_payment_id'),
        ('product_module', '0003_alter_brand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='product_module.product', verbose_name='محصول'),
        ),
    ]
