# Generated by Django 5.1.4 on 2025-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_module", "0003_rename_paid_data_ordermodel_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproductmodel",
            name="finally_price",
            field=models.BigIntegerField(null=True, verbose_name="قیمت نهایی محصول"),
        ),
    ]
