# Generated by Django 5.1.4 on 2025-04-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_module", "0004_alter_orderproductmodel_finally_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermodel",
            options={"verbose_name": "سبد خرید", "verbose_name_plural": "سبد های خرید"},
        ),
        migrations.AlterModelOptions(
            name="orderproductmodel",
            options={
                "verbose_name": "کالای سبد خرید",
                "verbose_name_plural": "کالاهای سبد خرید",
            },
        ),
        migrations.AddField(
            model_name="orderproductmodel",
            name="total_price",
            field=models.BigIntegerField(default=0, verbose_name="قیمت مجموع محصول"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderproductmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="order_module.ordermodel",
                verbose_name="سبد خرید",
            ),
        ),
    ]
