# Generated by Django 5.1.4 on 2025-04-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_alter_ordermodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductmodel',
            name='total_price',
        ),
    ]
