# Generated by Django 5.1.4 on 2026-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_module", "0006_remove_orderproductmodel_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "در انتظار پرداخت"),
                    ("pending_review", "در انتظار بررسی"),
                    ("preparing", "در حال آماده سازی"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل شده"),
                    ("returned", "مرجوعی"),
                ],
                default="pending_payment",
                max_length=255,
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
