# Generated by Django 5.1.4 on 2026-04-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_module", "0007_ordermodel_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermodel",
            options={
                "verbose_name": "سفارش / سبد خرید",
                "verbose_name_plural": "سفارش ها / سبد های خرید",
            },
        ),
    ]
