# Generated by Django 6.0.8 on 2026-09-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='Images/Banner', verbose_name='تصویر')),
                ('position', models.CharField(choices=[('product', 'صفحه محصولات'), ('contact', 'صفحه تماس با ما'), ('post_detail', 'صفحه جزییات مقاله '), ('product_detail', 'صفحه جزئیات محصول'), ('posts', 'صفحه مقالات')], max_length=200, verbose_name='محل قرار گیری در سایت')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس مقصد(اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تبلیغ سایت',
                'verbose_name_plural': 'تبلیعات سایت',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس مجموعه')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تلفن')),
                ('fax', models.CharField(max_length=255, verbose_name='فکس')),
                ('copy_right', models.CharField(max_length=255, verbose_name='متن کپی رایت')),
                ('about_us', models.TextField(verbose_name='متن درباره ما')),
                ('site_logo', models.ImageField(upload_to='Images/site_settings/', verbose_name='لوگو سایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان اسلایدر')),
                ('banner', models.ImageField(upload_to='Images/slider', verbose_name='عکس اسلایدر')),
                ('text', models.CharField(max_length=255, verbose_name='متن اسلایدر')),
                ('url', models.URLField(verbose_name='آدرس اسلایدر')),
                ('btn_text', models.CharField(max_length=25, verbose_name='متن دکمه اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
