# Generated by Django 5.1.4 on 2025-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس مجموعه')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تلفن')),
                ('fax', models.CharField(max_length=255, verbose_name='فکس')),
                ('copy_right', models.CharField(max_length=255, verbose_name='متن کپی رایت')),
                ('about_us', models.TextField(verbose_name='متن درباره ما')),
                ('site_logo', models.ImageField(upload_to='Images/site_settings/', verbose_name='لوگو سایت')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
