# Generated by Django 5.1.4 on 2025-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان اسلایدر')),
                ('banner', models.ImageField(upload_to='Images/slider', verbose_name='عکس اسلایدر')),
                ('text', models.CharField(max_length=255, verbose_name='متن اسلایدر')),
                ('url', models.URLField(verbose_name='آدرس اسلایدر')),
                ('btn_text', models.CharField(max_length=25, verbose_name='متن دکمه اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
