# Generated by Django 5.1.4 on 2025-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_delete_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='Images/Banner', verbose_name='تصویر')),
                ('position', models.CharField(choices=[('product', 'صفحه محصولات'), ('contact', 'صفحه تماس با ما'), ('blog', 'وبلاگ'), ('about', 'صفحه درباره ما'), ('product_detail', 'جزئیات محصول')], max_length=200, verbose_name='محل قرار گیری در سایت')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس مقصد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تبلیغ سایت',
                'verbose_name_plural': 'تبلیعات سایت',
            },
        ),
    ]
