# Generated by Django 5.1.4 on 2025-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitebanners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanners',
            name='position',
            field=models.CharField(choices=[('product', 'صفحه محصولات'), ('contact', 'صفحه تماس با ما'), ('blog', 'وبلاگ'), ('about', 'درباره ما'), ('product_detail', 'صفحه جزئیات محصول')], max_length=200, verbose_name='محل قرار گیری در سایت'),
        ),
    ]
