# Generated by Django 5.1.4 on 2025-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_sitebanners_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanners',
            name='position',
            field=models.CharField(choices=[('product', 'صفحه محصولات'), ('contact', 'صفحه تماس با ما'), ('post_detail', 'صفحه جزییات مقاله '), ('product_detail', 'صفحه جزئیات محصول'), ('posts', 'صفحه مقالات')], max_length=200, verbose_name='محل قرار گیری در سایت'),
        ),
    ]
