# Generated by Django 5.1.4 on 2025-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0007_alter_sitebanners_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
        ),
    ]
