# Generated by Django 5.1.4 on 2025-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0008_alter_sitesetting_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitebanners",
            name="url",
            field=models.URLField(
                blank=True, null=True, verbose_name="آدرس مقصد(اختیاری)"
            ),
        ),
    ]
