from django.urls import path

from . import views

urlpatterns = [
    path('', views.index_page, name="admin_index_page"),
    path('articles', views.ArticlePageView.as_view(), name="admin_articles_page"),
    path("article/<int:pk>", views.EditArticleView.as_view(), name="admin_article_detail_page"),
    path('contact-us/', views.ContactUSAdminView.as_view(), name="contact_us_admin_page"),
    path("contact-us/<int:pk>", views.MessageDetailView.as_view(), name="message-detail-page"),
    path('contact-us/remove-msg/', views.RemoveMessageAdminView.as_view(), name="remove_msg_from_admin_ajax"),
    path("contact-us/send-ans/", views.SendMsgAnswer.as_view(), name="send_ans_from_admin_ajax"),
    path("settings/slider/", views.sliderList.as_view(), name="sliders"),
    path("settings/slider/<int:pk>", views.sliderDetail.as_view(), name="slider_detail"),
    path("settings/add-slider/", views.addSliderView.as_view(), name="add_slider_page"),
    path("settings/slider/remove-slider/", views.RemoveSliderView.as_view(), name="remove_slider_page"),
    path("settings/slider/set-slider-enable/", views.SetSliderEnableView, name="set_slider_enable_ajax"),
    path("settings/slider/set-slider-disable/", views.SetSliderDisableView, name="set_slider_disable_ajax"),
    path("settings/site-setting/", views.SiteSettingEditView.as_view(), name="site_setting_page"),
    path("settings/banners/", views.BannersListView.as_view(), name="banners_list_page"),
    path("settings/banners/<int:pk>/", views.BannerEditPageView.as_view(), name="banner_edit_page"),
    path("settings/add-banner/", views.AddBannerView.as_view(), name="add_banner_page"),
    path("settings/banners/remove-banner/", views.RemoveBannerView.as_view(), name="remove_banner_ajax"),
    path("products/", views.ProductListView.as_view(), name="product_list_page"),
    path("products/remove-product/", views.RemoveProductViewAjax.as_view(), name="remove_product_ajax"),
    path("products/change-count/", views.change_product_count_ajax, name="change_product_count_ajax"),
    path("products/<int:pk>", views.ProductDetailView.as_view(), name="product_edit"),
    path("brands/", views.BrandListView.as_view(), name="brand_list_page"),
    path("brands/set-brand-enable/", views.SetBrandEnableView, name="set_brand_enable_ajax"),
    path("brands/set-brand-disable/", views.SetBrandDisableView, name="set_brand_disable_ajax"),
    path("brands/add-brand/", views.AddBrandPageView.as_view(), name="add_brand_page"),
    path("brands/remove-brand/", views.RemoveBrandAjax.as_view(), name="remove_brand_ajax"),
    path("brands/<int:pk>", views.BrandEditPageView.as_view(), name="edit_brand_page"),
    path("product-tags/set-product-tag-enable/", views.SetProductTagEnableView, name="set_product_tag_enable_ajax"),
    path("product-tags/set-product-tag-disable/", views.SetProductTagDisableView, name="set_product_tag_disable_ajax"),
    path("product-tags/", views.ProductBrandList.as_view(), name="product_tag_list_page"),
    path("product-tags/remove/", views.RemoveProductTagAjax.as_view(), name="remove_product_tag_ajax_admin"),
    path("product-tags/edit/<int:pk>", views.ProductTagEditPageView.as_view(), name="product_tag_edit_page"),

]
