# Generated by Django 6.0.8 on 2026-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_model',
            name='has_unread_reply',
            field=models.BooleanField(default=True, verbose_name='دارای پیام خوانده نشده '),
        ),
    ]
