# Generated by Django 5.1.4 on 2026-04-06 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ticket_attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("files", models.FileField(upload_to="tickets", verbose_name="پیوست")),
            ],
            options={
                "verbose_name": "پیوست تیکت",
                "verbose_name_plural": " پیوست های تیکت ها",
            },
        ),
        migrations.CreateModel(
            name="ticket_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان تیکت")),
                (
                    "Priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("medium", "متوسط"),
                            ("high", "اهمیت بالا"),
                        ],
                        max_length=255,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "Unit",
                    models.CharField(
                        choices=[
                            ("TechnicalUnit", "واحد فنی"),
                            ("FinancialUnit", "واحد مالی"),
                            ("OrderTracking", "پیگیری سفارش"),
                        ],
                        max_length=255,
                        verbose_name="واحد مربوطه",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="متن تیکت")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ساخت تیکت"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ بروزرسانی تیکت"
                    ),
                ),
                ("is_closed", models.BooleanField(verbose_name="بسته شدن تیکت")),
                ("is_active", models.BooleanField(verbose_name="فعال / غیرفعال")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": " تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
        migrations.DeleteModel(
            name="TicketModel",
        ),
        migrations.AddField(
            model_name="ticket_attachment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile_module.ticket_model",
                verbose_name="تیکت ها",
            ),
        ),
    ]
