# Generated by Django 5.1.4 on 2026-04-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile_module",
            "0002_ticket_attachment_ticket_model_delete_ticketmodel_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_model",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
        ),
    ]
