# Generated by Django 5.1.4 on 2026-04-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_module", "0003_alter_ticket_model_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_model",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="بسته شدن تیکت"),
        ),
    ]
