# Generated by Django 5.1.4 on 2026-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_module", "0005_ticketanswermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketanswermodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ثبت تیکت"
            ),
        ),
        migrations.AlterField(
            model_name="ticketanswermodel",
            name="text",
            field=models.TextField(verbose_name="متن پاسخ"),
        ),
    ]
