# Generated by Django 5.1.4 on 2026-04-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_module", "0006_ticketanswermodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_attachment",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile_module.ticket_model",
                verbose_name="تیکت ها",
            ),
        ),
    ]
