# Generated by Django 5.1.4 on 2026-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_module", "0007_alter_ticket_attachment_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket_attachment",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="زمان آپلود فایل"
            ),
        ),
    ]
