# Generated by Django 5.1.4 on 2025-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='خوانده شده'),
        ),
    ]
