# Generated by Django 6.0.8 on 2026-09-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='is_answer',
            field=models.BooleanField(default=False, verbose_name='پاسخ داده شده'),
        ),
    ]
