# Generated by Django 5.1.4 on 2025-03-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_alter_contactmodel_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
