# Generated by Django 5.1.4 on 2025-05-31 10:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_module", "0003_alter_contactmodel_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmodel",
            name="date",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ"
            ),
        ),
    ]
