# Generated by Django 6.0.8 on 2026-09-04 17:03

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_contactmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='answer_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
    ]
