from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="admin_home_page"),
    path("settings/", views.main_setting_page, name="admin_setting_page"),
    path("settings/setting", views.MainSetting.as_view(), name="admin_setting_main_page"),
    path("settings/ads", views.SettingsAdsView.as_view(), name="admin_ads_setting_page"),
    path("settings/ads/<id>", views.AdsEditView.as_view(), name="ads_edit_page"),
    path("settings/sliders", views.SliderListPage.as_view(), name="admin_sliders_list_page"),
    path("settings/sliders/<id>", views.SliderDetailView.as_view(), name="admin_slider_edit_page"),
    path("contact-us/", views.ContactUsListView.as_view(), name="admin_contact_us_list"),
    path("contact-us/<id>", views.ContactUsDetailView.as_view(), name="admin_contact_detail_page"),
    path("contact-us/send-answer/", views.send_msg_answer_ajax, name="admin_contact_send_email_ajax"),
    path("blog/list/", views.BlogListView.as_view(), name="admin_blog_list_page"),
    path("blog/add/", views.BlogAddPage.as_view(), name="admin_add_blog_post"),
    path("blog/categories/", views.ArticleCategoriesList.as_view(), name="admin_blog_categories"),
    path("blog/add-cat/", views.AddArticleCategory.as_view(), name="admin_add_blog_category"),
    path("blog/add-tag/", views.AddArticleTag.as_view(), name="admin_add_blog_tag"),
    path("blog/tags/", views.AdminBlogTagsList.as_view(), name="admin_blog_tags"),

    path("blog/<id>/", views.BlogEditPage.as_view(), name="admin_blog_edit_page"),
    path("blog/remove-cat/<id>", views.remove_category_ajax, name="admin_blog_remove_category"),
    path("blog/remove-tag/<id>", views.remove_tag_ajax, name="admin_blog_remove_tag"),
    path("blog/set-active-cat/<id>/", views.set_blog_cat_active, name="admin_category_blog_set_active"),
    path("blog/set-disable-cat/<id>/", views.set_blog_cat_disable, name="admin_category_blog_set_active"),
    path("blog/set-active-tag/<id>/", views.set_blog_tag_active, name="admin_tag_blog_set_active"),
    path("blog/set-disable-tag/<id>/", views.set_blog_tag_disable, name="admin_tag_blog_set_disable"),
    path("blog/comments/<post_id>", views.BlogPostCommentList.as_view(), name="admin_blog_post_comments"),
    path("blog/comment/<comment_id>", views.PostCommentDetail.as_view(), name="admin_comment_detail_page"),
    path("logout", views.admin_logout, name="admin_logout"),
    path("products/", views.ProductsListView.as_view(), name="admin_products_list"),
    path("products/add-cat/", views.AddProductCategory.as_view(), name="admin_add_product_category"),
    path("products/add-tag/", views.AddProductTag.as_view(), name="admin_add_product_tag"),
    path("products/add-brand/", views.AddProductBrand.as_view(), name="admin_add_product_brand"),
    path("products/remove-product/<id>/", views.remove_product_ajax, name="admin_remove_product"),
    path("products/comments/<product_id>/", views.ProductCommentList.as_view(), name="admin_product_comments"),
    path("products/comment/<comment_id>/", views.ProductCommentDetail.as_view(), name="admin_product_comment_detail"),
    path("products/brands/", views.ProductBrandList.as_view(), name="admin_product_brands"),
    path("products/tags/", views.AdminProductTagsList.as_view(), name="admin_product_tags_list"),
    path("products/remove-tag/<id>", views.remove_product_tag_ajax, name="admin_remove_product_tag"),
    path("products/set-active-tag/<id>/", views.set_product_tag_active, name="admin_set_active_tag"),
    path("products/set-disable-tag/<id>/", views.set_product_tag_disable, name="admin_set_disable_tag"),
    path("products/set-active-brand/<id>/", views.set_product_brand_active, name="admin_set_active_brand"),

    path("products/set-disable-brand/<id>/", views.set_product_brand_disable, name="admin_set_disable_brand"),

    path("products/<id>", views.ProductEditView.as_view(), name="admin_product_edit"),
    path("products/add/", views.AddProductView.as_view(), name="admin_product_add"),
    path("products/categorires/", views.ProductCategoriesList.as_view(), name="admin_product_categories_list"),
    path("products/remove-cat/<id>", views.remove_product_category_ajax, name="admin_remove_product_cat"),
    path("products/remove-brand/<id>", views.remove_product_brand_ajax, name="admin_remove_product_brand"),
    path("products/set-active-cat/<id>/", views.set_product_cat_active, name="admin_set_product_cat_active"),
    path("products/set-disable-cat/<id>/", views.set_product_cat_disable, name="admin_set_product_cat_disable"),
    path("products/remove-gallery/<id>/", views.remove_product_gallery_ajax, name="admin_remove_product_gallery"),
]
