# Generated by Django 5.1.4 on 2025-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="newsLetterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
                ),
            ],
            options={
                "verbose_name": "ایمیل خبرنامه",
                "verbose_name_plural": "ایمیل های خبرنامه",
            },
        ),
    ]
