# Generated by Django 6.0.8 on 2026-09-09 19:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermodel',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت خبرنامه'),
        ),
    ]
